name: .NET Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      builds-directory: ./builds
      server-directory: ./builds/server-build
      client-directory: ./builds/client-build
    
    steps:
    - name: Debug
      run: echo ${{ env.server-directory }}
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Install .NET
      run: sudo apt-get install -y dotnet-sdk-8.0

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Build server
      run: dotnet build pexeso-server -r win-x64 -o ${{ env.server-directory }}/win-x64 && dotnet build pexeso-server -r linux-x64 -o ${{ env.server-directory }}/linux-x64 && dotnet build pexeso-server -r osx-x64 -o ${{ env.server-directory }}/osx-x64
    
    - name: Build client
      run: dotnet build pexeso-client -r win-x64 -o ${{ env.client-directory }}/win-x64 && dotnet build pexeso-client -r linux-x64 -o ${{ env.client-directory }}/linux-x64 && dotnet build pexeso-client -r osx-x64 -o ${{ env.client-directory }}/osx-x64

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload server build
      uses: actions/upload-artifact@v3
      with:
        name: server_builds
        path: ${{ env.server-directory }}
        
    - name: Upload client build
      uses: actions/upload-artifact@v3
      with:
        name: client_builds
        path: ${{ env.client-directory }}
